services:

  api:
    build: "./api"
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./api:/home/node/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: "viptech"
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@viptech.com.br"
      PGADMIN_DEFAULT_PASSWORD: "viptech"
    ports:
      - "8080:80"
    volumes:
      - ./db/config:/var/lib/pgadmin
    depends_on:
      - db

